In [ ]:
# we need to convert the cate of the data. means converting string values of the data into numeric values because some algorithem 
# cannot read it

In [3]:
# we need to import labelencoder lib
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [4]:
data = pd.read_csv('../data.csv')

In [5]:
data

,trip_id,year,month,week,day,hour,usertype,gender,starttime,stoptime,...,from_station_id,from_station_name,latitude_start,longitude_start,dpcapacity_start,to_station_id,to_station_name,latitude_end,longitude_end,dpcapacity_end
0,2355134,2014,6,27,0,23,Subscriber,Male,2014-06-30 23:57:00,2014-07-01 00:07:00,...,131,Lincoln Ave & Belmont Ave,41.939365,-87.668385,15.0,303,Broadway & Cornelia Ave,41.945512,-87.645980,15.0
1,2355133,2014,6,27,0,23,Subscriber,Male,2014-06-30 23:56:00,2014-07-01 00:00:00,...,282,Halsted St & Maxwell St,41.864580,-87.646930,15.0,22,May St & Taylor St,41.869482,-87.655486,15.0
2,2355130,2014,6,27,0,23,Subscriber,Male,2014-06-30 23:33:00,2014-06-30 23:35:00,...,327,Sheffield Ave & Webster Ave,41.921687,-87.653714,19.0,225,Halsted St & Dickens Ave,41.919936,-87.648830,15.0
3,2355129,2014,6,27,0,23,Subscriber,Female,2014-06-30 23:26:00,2014-07-01 00:24:00,...,134,Peoria St & Jackson Blvd,41.877749,-87.649633,19.0,194,State St & Wacker Dr,41.887155,-87.627750,11.0
4,2355128,2014,6,27,0,23,Subscriber,Female,2014-06-30 23:16:00,2014-06-30 23:26:00,...,320,Loomis St & Lexington St,41.872187,-87.661501,15.0,134,Peoria St & Jackson Blvd,41.877749,-87.649633,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495230,16734072,2017,10,39,6,0,Subscriber,Female,2017-10-01 00:01:00,2017-10-01 00:12:00,...,220,Hampden Ct & Diversey Pkwy,41.932620,-87.642385,23.0,87,Racine Ave & Fullerton Ave,41.925563,-87.658404,19.0
9495231,16734071,2017,10,39,6,0,Subscriber,Male,2017-10-01 00:01:00,2017-10-01 00:12:00,...,220,Hampden Ct & Diversey Pkwy,41.932620,-87.642385,23.0,87,Racine Ave & Fullerton Ave,41.925563,-87.658404,19.0
9495232,16734070,2017,10,39,6,0,Subscriber,Male,2017-10-01 00:01:00,2017-10-01 00:15:00,...,289,Wells St & Concord Ln,41.912133,-87.634656,19.0,226,Racine Ave & Belmont Ave,41.939743,-87.658865,15.0
9495233,16734067,2017,10,39,6,0,Subscriber,Female,2017-10-01 00:00:00,2017-10-01 00:06:00,...,288,Larrabee St & Armitage Ave,41.918084,-87.643749,11.0,289,Wells St & Concord Ln,41.912133,-87.634656,19.0
9495234,16734066,2017,10,39,6,0,Subscriber,Female,2017-10-01 00:00:00,2017-10-01 00:12:00,...,135,Halsted St & 21st St,41.853780,-87.646650,11.0,129,Blue Island Ave & 18th St,41.857556,-87.661535,15.0

In [11]:
x = data[['gender','usertype']].values
print(x)

[['Male' 'Subscriber']
 ['Male' 'Subscriber']
 ['Male' 'Subscriber']
 ...
 ['Male' 'Subscriber']
 ['Female' 'Subscriber']
 ['Female' 'Subscriber']]

In [12]:
data_encoding_x = LabelEncoder()

In [13]:
data_encoding_x.fit_transform(x[:,0])

array([1, 1, 1, ..., 1, 0, 0])

In [15]:
x[:,0] = data_encoding_x.fit_transform(x[:,0])
print(x)

[[1 'Subscriber']
 [1 'Subscriber']
 [1 'Subscriber']
 ...
 [1 'Subscriber']
 [0 'Subscriber']
 [0 'Subscriber']]